[project]
name = "maintenance-tracker"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dateparser>=1.4.1",
    "human-readable>=2.0.3",
    "typer>=0.27.0",
]

[dependency-groups]
dev = [
    "freezegun>=1.5.5",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "black>=23.1.0",
    "pyright>=1.1.300",
]
